= PXE - Server

El servidor PXE (Preboot eXecution Environment) permite la instalación desatendida o automatizada del sistema operativo a 
través de la red. El principal beneficio de pxe es que no necesitamos ninguna unidad de arranque para iniciar l instalación 
un sistema operativo (SO) y no necesitamos grabar ningún archivo ISO en DVD o dispositivo usb.

Una vez que el servidor PXE está configurado, podemos instalar una gran cantidad de sistemas al mismo tiempo en la red. 
Como funciona en la arquitectura de cliente-servidor, para obtener la instalación del sistema operativo en los clientes, 
inicie los clientes a través de la opción PXE (boot via network).

En este artículo vamos a configurar el servidor PXE en CentOS 7.x y luego instalar el sistema operativo en el cliente 
utilizando pxe boot.

Información del equipo

----
KVM Virtual MAchine
IP = 192.168.122.10
Hostname = pxe.themike.systems
Distribución = CentOS 7.x
SELinux = habilitado
Firewall = ha
----

1 .- Instalar paquetes necesarios por PXE.

Para instalar y configurar el servidor pxe en centos 7.x, necesitamos los siguientes paquetes "dhcp, tftp-server, ftp server (vsftpd), xinted".

----
[root@pxe ~]# yum install dhcp tftp tftp-server syslinux vsftpd xinetd
----

2 .- Configurar servidor DHCP para PXE
Cuando instalamos el paquete dhcp, se crea un archivo de configuración '/etc/dhcp/dhcpd.conf'.

Copie las siguientes líneas en el archivo '/etc/dhcp/dhcpd.conf', reemplace la subred ip y otros detalles según su entorno.

----
[root@pxe ~]# vi /etc/dhcp/dhcpd.conf

# DHCP Server Configuration file.

ddns-update-style interim;
ignore client-updates;
authoritative;
allow booting;
allow bootp;
allow unknown-clients;

# internal subnet for my DHCP Server
subnet 10.17.32.0 netmask 255.255.255.0 {
range 10.17.32.20 10.17.32.50;
option domain-name-servers 10.17.32.6;
option domain-name "pxe.themike.systems";
option routers 10.17.32.254;
option broadcast-address 10.17.32.255;
default-lease-time 600;
max-lease-time 7200;

# IP of PXE Server
next-server 10.17.32.5;
filename "pxelinux.0";
}
----

3 .- Editar y configurar servidor tftp (/etc/xinetd.d/tftp)
TFTP (Trivial File Transfer Protocol) se utiliza para transferir archivos del servidor a sus clientes sin ningún tipo de autenticación. En el caso de la configuración del servidor PXE, tftp se usa para la carga de bootstrap. Para configurar el servidor tftp, edite su archivo de configuración '/etc/xinetd.d/tftp', cambie el parámetro 'disable = yes' por 'disable = no'.

----
[root@pxe ~]# vi /etc/xinetd.d/tftp
service tftp
{
 socket_type = dgram
 protocol    = udp
 wait        = yes
 user        = root
 server      = /usr/sbin/in.tftpd
 server_args = -s /var/lib/tftpboot
 disable     = no
 per_source  = 11
 cps         = 100 2
 flags       = IPv4
}
----
Todos los archivos relacionados con el inicio de red deben colocarse en el directorio de tftp "/var/lib/tftpboot"

Ejecute los siguientes comandos para copiar los archivos de inicio de red requeridos en '/var/lib/tftpboot/'

----
[root@pxe ~]# cp /usr/share/syslinux/pxelinux.0 /var/lib/tftpboot
[root@pxe ~]# cp /usr/share/syslinux/menu.c32 /var/lib/tftpboot
[root@pxe ~]# cp /usr/share/syslinux/memdisk /var/lib/tftpboot
[root@pxe ~]# cp /usr/share/syslinux/mboot.c32 /var/lib/tftpboot
[root@pxe ~]# cp /usr/share/syslinux/chain.c32 /var/lib/tftpboot
[root@pxe ~]# mkdir /var/lib/tftpboot/pxelinux.cfg
[root@pxe ~]# mkdir /var/lib/tftpboot/networkboot

----

4 .- Monte la imagen ISO de CentOS 7.x y copie su contenido al servidor ftp.
Monte la imagen iso y luego copie su contenido en el directorio del servidor ftp '/var/ftp/pub'
----
[root@pxe ~]# mount -o loop CentOS-7-x86_64.iso /mnt/
[root@pxe ~]# cd /mnt/
[root@pxe mnt]# cp -av * /var/ftp/pub/
[root@pxe ~]# cp /mnt/images/pxeboot/vmlinuz /var/lib/tftpboot/networkboot/
[root@pxe ~]# cp /mnt/images/pxeboot/initrd.img /var/lib/tftpboot/networkboot/
[root@pxe ~]# umount /mnt/
----
5 .- Crear el archivo kickStart & Menu PXE.
----
[root@pxe ~]# openssl passwd -1 Pa55w0rd
----
El archivo kickstart predeterminado del sistema se coloca en /root con el nombre 'anaconda-ks.cfg'.
----
[root@pxe ~]# vi /var/ftp/pub/anaconda-ks.cfg

#platform=x86, AMD64, or Intel EM64T
#version=DEVEL
# Firewall configuration
firewall --disabled
# Install OS instead of upgrade
install
# Use FTP installation media
url --url="ftp://172.168.1.11/pub/"
# Root password
rootpw --iscrypted $1$e2wrcGGX$tZPQKPsXVhNmbiGg53MN41
# System authorization information
auth useshadow passalgo=sha512
# Use graphical install
graphical
firstboot disable
# System keyboard
keyboard us
# System language
lang en_US
# SELinux configuration
selinux disabled
# Installation logging level
logging level=info
# System timezone
timezone Europe/Amsterdam
# System bootloader configuration
bootloader location=mbr
clearpart --all --initlabel
part swap --asprimary --fstype="swap" --size=1024
part /boot --fstype xfs --size=300
part pv.01 --size=1 --grow
volgroup root_vg01 pv.01
logvol / --fstype xfs --name=lv_01 --vgname=root_vg01 --size=1 --grow
%packages
@^minimal
@core
%end
%addon com_redhat_kdump --disable --reserve-mb='auto'
%end
----
Cree un archivo de menú PXE (/var/lib/tftpboot/pxelinux.cfg/default).
----
[root@pxe ~]# vi /var/lib/tftpboot/pxelinux.cfg/default

default menu.c32
prompt 0
timeout 30
MENU TITLE LinuxTechi.com PXE Menu
LABEL centos7_x64
MENU LABEL CentOS 7_X64
KERNEL /networkboot/vmlinuz
APPEND initrd=/networkboot/initrd.img inst.repo=ftp://10.17.32.5/pub ks=ftp://10.17.32.5/pub/centos7.cfg
----
6 .- Inicie y habilite el servicio xinetd, dhcp y vsftpd.
----
[root@pxe ~]# systemctl start xinetd.service dhcpd.service vsftpd.service
[root@pxe ~]# systemctl enable xinetd.service dhcpd.service vsftpd.service
----
En caso de que SELinux esté habilitado, configure la siguiente regla de selinux para el servidor ftp.
----
[root@pxe ~]# setsebool -P ftpd_full_access on
----
Abra los puertos en el firewall del SO con los siguientes comandos firewall-cmd
----
[root@pxe ~]# firewall-cmd --add-service=ftp --permanent
[root@pxe ~]# firewall-cmd --add-service=dhcp --permanent
[root@pxe ~]# firewall-cmd --add-port=69/tcp --permanent 
[root@pxe ~]# firewall-cmd --add-port=69/udp --permanent 
[root@pxe ~]# firewall-cmd --add-port=4011/udp --permanent
[root@pxe ~]# firewall-cmd --reload
----
Hasta este momento, la instalación y configuración del servidor PXE se completa ahora.

7 .- Arranque los clientes con la opción de arranque PXE.
